version: 2

models:
    - name: coverage
      description: Coverage details
      config:
        schema: "{{ var('data_set')}}_core"
      tests:
         - unique:
             column_name: "(patient_id || payer || coverage_start_date || coverage_end_date)"
      columns:
        - name: patient_id  
          description: unique identifier