version: 2

models:
    - name: eligibility
      description: eligibility details
      config:
        database: "{{ var('output_database')}}"
        schema: "{{ var('output_schema')}}"
      tests:
         - unique:
            column_name: "(patient_id || member_id || payer || payer_type || enrollment_start_date || enrollment_end_date)"
            config:
              severity: error
      columns:
        - name: patient_id  
          description: unique identifier