version: 2

models:
    - name: acute_inpatient_encounter
      description: Mapping of acute inpatient encounter
      config:
        database: "{{ var('output_database')}}"
        schema: "{{ var('output_schema')}}"
      columns:
        - name: claim_id
          description: Claim id from data source and primary key
          tests:
            - unique
            - not_null