version: 2

models:
    - name: encounter_inst_stage
      description: Encounter level data elements for institutional claims
      config:
        schema: "{{ var('output_schema')}}"
      columns:
        - name: encounter_id
          description: Unique identifier
          tests:
            - unique
            - not_null