version: 2

models:
    - name: encounter_claim_crosswalk
      description: A crosswalk between encounter_id, new claim id, and original claim id
      config:
        schema: "{{ var('data_set')}}_claims_preprocessing"