version: 2

models:
    - name: encounter_claim_crosswalk
      description: A crosswalk between encounter id and  claim id
      config:
        database: "{{ var('output_database')}}"
        schema: "{{ var('output_schema')}}"
