version: 2

models:
    - name: inst_merge_final
      description: Encounter details
      config:
        database: "{{ var('output_database')}}"
        schema: "{{ var('output_schema')}}"
      tests:
         - unique:
             column_name: "claim_id_b"
      columns:
        - name: patient_id  
          description: unique identifier