version: 2

models:
    - name: inst_encounter_final
      description: All encounters for institutional claims.
      config:
        schema: "{{ var('output_schema')}}"
      columns:
        - name: encounter_id
          description:  Unique identifer for the encounter and primary key
          tests:
            - unique
            - not_null