version: 2

models:
    - name: prof_inst_encounter_crosswalk
      description: List of institutional claims pairs that are eligable for merging.
      config:
        database: "{{ var('output_database')}}"
        schema: "{{ var('output_schema')}}"