version: 2

models:
    - name: prof_merge_crosswalk
      description: List of institutional claims pairs that are eligable for merging.
      config:
        schema: "{{ var('source_name')}}_{{ var('output_schema')}}"