version: 2

sources:
  - name: "{{ var('source_name') }}"
    database: "{{ var('input_database') }}"
    schema:  "{{ var('input_schema') }}"
    tables:
      - name: tn_medical_claim
      - name: eligibility
